# Generated by Django 3.2.12 on 2022-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kerdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerdes', models.CharField(max_length=256)),
                ('valasz1', models.CharField(max_length=256)),
                ('valasz2', models.CharField(max_length=256)),
                ('valasz3', models.CharField(max_length=256)),
                ('valasz4', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Kérdés',
                'verbose_name_plural': 'Kérdések',
            },
        ),
    ]
